In [1]:
import pandas as pd

In [ ]:
import numpy as np

# Series
series 는 pandas의 1차원 데이터타입을 말합니다.

In [4]:
series = pd.Series([1, 3, 5, np.nan, 7, 9])
series

0    1.0
1    3.0
2    5.0
3    NaN
4    7.0
5    9.0
dtype: float64

In [6]:
series[series<5]

0    1.0
1    3.0
dtype: float64

# DataFrame
DataFrame 은 pandas 의 2차원 데이터타입을 말합니다.

In [7]:
data = {'Name' : 'Seoyoon',
        'Age' : 25,
        'Height' : 180.2,
        'Weight' : 60.8,
        'Job' : 'Student'}
data

{'Name': 'Seoyoon',
 'Age': 25,
 'Height': 180.2,
 'Weight': 60.8,
 'Job': 'Student'}

In [10]:
columns = ['Name', 'Age', 'Height', 'Weight', 'Job']

In [13]:
# index는 임의로 0으로 두었다.
df = [pd.DataFrame(data = data, index = [0], columns = columns)]
df

[      Name  Age  Height  Weight      Job
 0  Seoyoon   25   180.2    60.8  Student]

In [14]:
multi_data = {'Name' : ['Seoyoon', 'Hyunmin'],
        'Age' : [25, 26],
        'Height' : [180.2, 168.7],
        'Weight' : [60.8, 54.3],
        'Job' : ['Student', 'Job seeker']}
multi_data

{'Name': ['Seoyoon', 'Hyunmin'],
 'Age': [25, 26],
 'Height': [180.2, 168.7],
 'Weight': [60.8, 54.3],
 'Job': ['Student', 'Job seeker']}

In [19]:
# index는 임의로 0으로 두었다.
multi_df = [pd.DataFrame(data = multi_data, index = range(0,2), columns = columns)]
multi_df

[      Name  Age  Height  Weight         Job
 0  Seoyoon   25   180.2    60.8     Student
 1  Hyunmin   26   168.7    54.3  Job seeker]

In [20]:
csv_path = 'wine_dataset.csv'

In [21]:
import os

In [26]:
os.listdir("sample") # ls 명령어 (path)

['bigstock-Group-Of-Animals-34563776.jpg',
 'nums_keywords.xlsx',
 'Relevant keywords 20190212 2313.xlsx',
 'resume template.docx',
 'resume template.hwp',
 'resume template.pdf',
 't1.daumcdn.png',
 'tiger.jpg',
 'wine_dataset.csv',
 '「인공지능 업무자동화교육」 참가신청서.docx',
 '「인공지능 업무자동화교육」 참가신청서.hwp',
 '「인공지능 업무자동화교육」 참가신청서.pdf']

In [32]:
import glob
glob.glob("Un")

[]

In [33]:
df = pd.read_csv(csv_path)
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.640000,1.04,3.92,1065.0,0.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.380000,1.05,3.40,1050.0,0.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.680000,1.03,3.17,1185.0,0.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.800000,0.86,3.45,1480.0,0.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.320000,1.04,2.93,735.0,0.0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.750000,1.05,2.85,1450.0,0.0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.250000,1.02,3.58,1290.0,0.0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.050000,1.06,3.58,1295.0,0.0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.200000,1.08,2.85,1045.0,0.0
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.220000,1.01,3.55,1045.0,0.0
10,14.10,2.16,2.30,18.0,105.0,2.95,3.32,0.22,2.38,5.750000,1.25,3.17,1510.0,0.0
11,14.12,1.48,2.32,16.8,95.0,2.20,2.43,0.26,1.57,5.000000,1.17,2.82,1280.0,0.0
12,13.75,1.73,2.41,16.0,89.0,2.60,2.76,0.29,1.81,5.600000,1.15,2.90,1320.0,0.0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.400000,1.25,2.73,1150.0,0.0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.500000,1.20,3.00,1547.0,0.0
15,13.63,1.81,2.70,17.2,112.0,2.85,2.91,0.30,1.46,7.300000,1.28,2.88,1310.0,0.0
16,14.30,1.92,2.72,20.0,120.0,2.80,3.14,0.33,1.97,6.200000,1.07,2.65,1280.0,0.0
17,13.83,1.57,2.62,20.0,115.0,2.95,3.40,0.40,1.72,6.600000,1.13,2.57,1130.0,0.0
18,14.19,1.59,2.48,16.5,108.0,3.30,3.93,0.32,1.86,8.700000,1.23,2.82,1680.0,0.0
19,13.64,3.10,2.56,15.2,116.0,2.70,3.03,0.17,1.66,5.100000,0.96,3.36,845.0,0.0
20,14.06,1.63,2.28,16.0,126.0,3.00,3.17,0.24,2.10,5.650000,1.09,3.71,780.0,0.0
21,12.93,3.80,2.65,18.6,102.0,2.41,2.41,0.25,1.98,4.500000,1.03,3.52,770.0,0.0
22,13.71,1.86,2.36,16.6,101.0,2.61,2.88,0.27,1.69,3.800000,1.11,4.00,1035.0,0.0
23,12.85,1.60,2.52,17.8,95.0,2.48,2.37,0.26,1.46,3.930000,1.09,3.63,1015.0,0.0
24,13.50,1.81,2.61,20.0,96.0,2.53,2.61,0.28,1.66,3.520000,1.12,3.82,845.0,0.0
25,13.05,2.05,3.22,25.0,124.0,2.63,2.68,0.47,1.92,3.580000,1.13,3.20,830.0,0.0
26,13.39,1.77,2.62,16.1,93.0,2.85,2.94,0.34,1.45,4.800000,0.92,3.22,1195.0,0.0
27,13.30,1.72,2.14,17.0,94.0,2.40,2.19,0.27,1.35,3.950000,1.02,2.77,1285.0,0.0
28,13.87,1.90,2.80,19.4,107.0,2.95,2.97,0.37,1.76,4.500000,1.25,3.40,915.0,0.0
29,14.02,1.68,2.21,16.0,96.0,2.65,2.33,0.26,1.98,4.700000,1.04,3.59,1035.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,13.32,3.24,2.38,21.5,92.0,1.93,0.76,0.45,1.25,8.420000,0.55,1.62,650.0,2.0
149,13.08,3.90,2.36,21.5,113.0,1.41,1.39,0.34,1.14,9.400000,0.57,1.33,550.0,2.0
150,13.50,3.12,2.62,24.0,123.0,1.40,1.57,0.22,1.25,8.600000,0.59,1.30,500.0,2.0
151,12.79,2.67,2.48,22.0,112.0,1.48,1.36,0.24,1.26,10.800000,0.48,1.47,480.0,2.0
152,13.11,1.90,2.75,25.5,116.0,2.20,1.28,0.26,1.56,7.100000,0.61,1.33,425.0,2.0
153,13.23,3.30,2.28,18.5,98.0,1.80,0.83,0.61,1.87,10.520000,0.56,1.51,675.0,2.0
154,12.58,1.29,2.10,20.0,103.0,1.48,0.58,0.53,1.40,7.600000,0.58,1.55,640.0,2.0
155,13.17,5.19,2.32,22.0,93.0,1.74,0.63,0.61,1.55,7.900000,0.60,1.48,725.0,2.0
156,13.84,4.12,2.38,19.5,89.0,1.80,0.83,0.48,1.56,9.010000,0.57,1.64,480.0,2.0
157,12.45,3.03,2.64,27.0,97.0,1.90,0.58,0.63,1.14,7.500000,0.67,1.73,880.0,2.0
158,14.34,1.68,2.70,25.0,98.0,2.80,1.31,0.53,2.70,13.000000,0.57,1.96,660.0,2.0
159,13.48,1.67,2.64,22.5,89.0,2.60,1.10,0.52,2.29,11.750000,0.57,1.78,620.0,2.0
160,12.36,3.83,2.38,21.0,88.0,2.30,0.92,0.50,1.04,7.650000,0.56,1.58,520.0,2.0
161,13.69,3.26,2.54,20.0,107.0,1.83,0.56,0.50,0.80,5.880000,0.96,1.82,680.0,2.0
162,12.85,3.27,2.58,22.0,106.0,1.65,0.60,0.60,0.96,5.580000,0.87,2.11,570.0,2.0
163,12.96,3.45,2.35,18.5,106.0,1.39,0.70,0.40,0.94,5.280000,0.68,1.75,675.0,2.0
164,13.78,2.76,2.30,22.0,90.0,1.35,0.68,0.41,1.03,9.580000,0.70,1.68,615.0,2.0
165,13.73,4.36,2.26,22.5,88.0,1.28,0.47,0.52,1.15,6.620000,0.78,1.75,520.0,2.0
166,13.45,3.70,2.60,23.0,111.0,1.70,0.92,0.43,1.46,10.680000,0.85,1.56,695.0,2.0
167,12.82,3.37,2.30,19.5,88.0,1.48,0.66,0.40,0.97,10.260000,0.72,1.75,685.0,2.0
168,13.58,2.58,2.69,24.5,105.0,1.55,0.84,0.39,1.54,8.660000,0.74,1.80,750.0,2.0
169,13.40,4.60,2.86,25.0,112.0,1.98,0.96,0.27,1.11,8.500000,0.67,1.92,630.0,2.0
170,12.20,3.03,2.32,19.0,96.0,1.25,0.49,0.40,0.73,5.500000,0.66,1.83,510.0,2.0
171,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,2.0
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.700000,0.62,1.71,660.0,2.0
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.700000,0.64,1.74,740.0,2.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.300000,0.70,1.56,750.0,2.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.200000,0.59,1.56,835.0,2.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.300000,0.60,1.62,840.0,2.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.200000,0.61,1.60,560.0,2.0

# df slice

In [36]:
# 맨 위 다섯 개
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0.0

In [35]:
# 맨 아래 다섯 개
df.tail()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740.0,2.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750.0,2.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835.0,2.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840.0,2.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560.0,2.0

In [47]:
# 10 번째부터 16번째 것까지
df[10:16]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
10,14.10,2.16,2.30,18.0,105.0,2.95,3.32,0.22,2.38,5.75,1.25,3.17,1510.0,0.0
11,14.12,1.48,2.32,16.8,95.0,2.20,2.43,0.26,1.57,5.00,1.17,2.82,1280.0,0.0
12,13.75,1.73,2.41,16.0,89.0,2.60,2.76,0.29,1.81,5.60,1.15,2.90,1320.0,0.0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0.0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0.0
15,13.63,1.81,2.70,17.2,112.0,2.85,2.91,0.30,1.46,7.30,1.28,2.88,1310.0,0.0

In [37]:
df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
alcohol                         178 non-null float64
malic_acid                      178 non-null float64
ash                             178 non-null float64
alcalinity_of_ash               178 non-null float64
magnesium                       178 non-null float64
total_phenols                   178 non-null float64
flavanoids                      178 non-null float64
nonflavanoid_phenols            178 non-null float64
proanthocyanins                 178 non-null float64
color_intensity                 178 non-null float64
hue                             178 non-null float64
od280/od315_of_diluted_wines    178 non-null float64
proline                         178 non-null float64
target                          178 non-null float64
dtypes: float64(14)
memory usage: 19.5 KB

In [39]:
df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [40]:
df.columns[2:4]

Index(['ash', 'alcalinity_of_ash'], dtype='object')

In [45]:
df[['alcohol', 'ash']]

   alcohol   ash
0    14.23  2.43
1    13.20  2.14
2    13.16  2.67
3    14.37  2.50
4    13.24  2.87

In [45]:
df[['alcohol', 'ash']].head()

   alcohol   ash
0    14.23  2.43
1    13.20  2.14
2    13.16  2.67
3    14.37  2.50
4    13.24  2.87

In [51]:
df[['alcohol', 'ash']][10:16]

    alcohol   ash
10    14.10  2.30
11    14.12  2.32
12    13.75  2.41
13    14.75  2.39
14    14.38  2.38
15    13.63  2.70

In [46]:
df.index

RangeIndex(start=0, stop=178, step=1)

In [52]:
df[df['alcohol']>14]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0.0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0,0.0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0.0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0,0.0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0.0
10,14.10,2.16,2.30,18.0,105.0,2.95,3.32,0.22,2.38,5.75,1.25,3.17,1510.0,0.0
11,14.12,1.48,2.32,16.8,95.0,2.20,2.43,0.26,1.57,5.00,1.17,2.82,1280.0,0.0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0.0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0.0
16,14.30,1.92,2.72,20.0,120.0,2.80,3.14,0.33,1.97,6.20,1.07,2.65,1280.0,0.0
18,14.19,1.59,2.48,16.5,108.0,3.30,3.93,0.32,1.86,8.70,1.23,2.82,1680.0,0.0
20,14.06,1.63,2.28,16.0,126.0,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780.0,0.0
29,14.02,1.68,2.21,16.0,96.0,2.65,2.33,0.26,1.98,4.70,1.04,3.59,1035.0,0.0
39,14.22,3.99,2.51,13.2,128.0,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760.0,0.0
45,14.21,4.04,2.44,18.9,111.0,2.85,2.65,0.30,1.25,5.24,0.87,3.33,1080.0,0.0
46,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0,0.0
48,14.10,2.02,2.40,18.8,103.0,2.75,2.92,0.32,2.38,6.20,1.07,2.75,1060.0,0.0
56,14.22,1.70,2.30,16.3,118.0,3.20,3.00,0.26,2.03,6.38,0.94,3.31,970.0,0.0
158,14.34,1.68,2.70,25.0,98.0,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660.0,2.0
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660.0,2.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2.0

In [53]:
# list 안의 값 세 개 중에 하나라도 해당하면 true
df['alcohol'].isin([14.23, 14.20, 14.22])

0       True
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
Name: alcohol, Length: 178, dtype: bool

# Math

In [54]:
df.mean()

alcohol                          13.000618
malic_acid                        2.336348
ash                               2.366517
alcalinity_of_ash                19.494944
magnesium                        99.741573
total_phenols                     2.295112
flavanoids                        2.029270
nonflavanoid_phenols              0.361854
proanthocyanins                   1.590899
color_intensity                   5.058090
hue                               0.957449
od280/od315_of_diluted_wines      2.611685
proline                         746.893258
target                            0.938202
dtype: float64

In [55]:
a = df.median()

In [56]:
a

alcohol                          13.050
malic_acid                        1.865
ash                               2.360
alcalinity_of_ash                19.500
magnesium                        98.000
total_phenols                     2.355
flavanoids                        2.135
nonflavanoid_phenols              0.340
proanthocyanins                   1.555
color_intensity                   4.690
hue                               0.965
od280/od315_of_diluted_wines      2.780
proline                         673.500
target                            1.000
dtype: float64

# 직접 어떤 식을 데이터프레임에 적용하고 싶을 때

In [57]:
def norm(x):
    return x.max() - x.min()
df.apply(norm)

alcohol                            3.80
malic_acid                         5.06
ash                                1.87
alcalinity_of_ash                 19.40
magnesium                         92.00
total_phenols                      2.90
flavanoids                         4.74
nonflavanoid_phenols               0.53
proanthocyanins                    3.17
color_intensity                   11.72
hue                                1.23
od280/od315_of_diluted_wines       2.73
proline                         1402.00
target                             2.00
dtype: float64

In [58]:
# 위 블럭과 똑같음
df.apply(lambda x: x.max() - x.min())

alcohol                            3.80
malic_acid                         5.06
ash                                1.87
alcalinity_of_ash                 19.40
magnesium                         92.00
total_phenols                      2.90
flavanoids                         4.74
nonflavanoid_phenols               0.53
proanthocyanins                    3.17
color_intensity                   11.72
hue                                1.23
od280/od315_of_diluted_wines       2.73
proline                         1402.00
target                             2.00
dtype: float64